### PR TITLE
Add Bootstrap 5.3.2

### PR DESCRIPTION
**Pull request by cal0pteryx**

### CODE REVIEW

**Comment by cal0pteryx** [comment]
@mwild1 what about this one? :)

**Comment by Zash** [comment]
Why is this needed?

**Comment by cal0pteryx** [comment]
Without Bootstrap being present in the repository, a `git clone` yields a broken website. A potential developer would then have to figure out why it's broken by default, and then after figuring that out, which version of Bootstrap to download and add (manually).

**Comment by cal0pteryx** [comment]
Same goes for `FileSaver.min.js` , which is already checked-in.

**Comment by cal0pteryx** [comment]
@mwild1 ping :)

**Pull request merged**
